#oxocarbon theme remix

[colors.bright]
black = "#222020"
blue = "#25439e"
cyan = "#228483"
green = "#328545"
magenta = "#694c9e"
red = "#922a4d"
white = "#5c5959"
yellow = "#9e3f43"

[colors.cursor]
cursor = "#9e9e9e"

[colors.normal]
black = "#171616"
blue = "#37599e"
cyan = "#0e5250"
green = "#155526"
magenta = "#57319e"
red = "#922a4d"
white = "#333131"
yellow = "#9a282b"

[colors.primary]
background = "#171414"
foreground = "#6d6a6a"

